### ISSUE TITLE
Used trust wallet to bridge but cannot switch network

### ISSUE THREAD

**Issue by LinkTheLion** [raid-guild/xdai-omnibridge#103]
I’m sorry if this is basic to you all. But I used trust wallet to bridge Erc 20 tokens. Unfortunately I cannot interact with bridged tokens, as I can’t switch to xdai network with trust wallet.

**Comment by scottrepreneur** [comment]
Trust wallet doesn't support custom RPCs directly. Try Metamask Mobile or another wallet that supports custom networks to interact with xDai.

**Comment by LinkTheLion** [comment]
But how do I access the funds I already transferred?

**Comment by scottrepreneur** [comment]
You'll need to use a wallet like Metamask Mobile or others that allow you to set the custom RPC necessary for connecting to xDai.

**Comment by dan13ram** [comment]
Your funds are not linked to your trustwallet account but rather your
private key used to access your trustwallet.
You can use the same private key to access other your funds using other
wallets as mentioned above.
