### ISSUE TITLE
custom token swap

### ISSUE THREAD

**Issue by mwalol** [raid-guild/xdai-omnibridge#104]
i have add a custom token to swap but it show an error  : 0x969ee7e66bd4f3b4460e957ca583a2e09fa84ddd

![image](https://user-images.githubusercontent.com/7727649/96317206-18b4fb80-100f-11eb-9026-37c31cb94bfb.png)

any idea why?

**Comment by scottrepreneur** [comment]
Hmm weird. Can you try a little less than your balance? It might be trying to send too close to your exact balance.

**Comment by mwalol** [comment]
i did tried little balance, but same issue.

well i have sold that token for now, since i was trying to do some arbitrage but seem i'm out of luck
