### ISSUE TITLE
walletconnect passing undefined to functions

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/xdai-omnibridge#141]
I'm having trouble getting the bridge to play nicely with the Gnosis Safe via walletconnect.

Connecting the safe to the bridge brings in the right balances and confirms the allowance, but sending the functions returns an error. Happens on both unlock and transfer calls currently.

- Connect via WalletConnect to Gnosis Safe
- switch to token (WETH)
- attempt to unlock max
- if unlocked, attempt to transfer (relay)

`"invalid BigNumber value (argument="value", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.0.12)"`

**Comment by dan13ram** [comment]
Fixed in #142
