### ISSUE TITLE
Retrieve historical transactions

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/xdai-omnibridge#15]
Retrieve the user's historical transactions on the current network and show them on the History page.

- Link to block explorer for the current network
- Need separate links for ALM and Etherscan?

<img width="1084" alt="Screen Shot 2020-08-29 at 11 34 39 AM" src="https://user-images.githubusercontent.com/1778380/91643316-a0ab5b80-e9f7-11ea-9cda-a891f055ef91.png">

**Comment by dan13ram** [comment]
These links will only be transaction links to either etherscan/blockscout based on the network selected.
Will also require setting up a subgraph for easier retrieval and pagination perhaps.

ALM flow is only for 8 transaction confirmations for Eth-to-xDai and only 2 from xDai-to-Eth and are handled here:
 
![Screenshot from 2020-08-30 05:53:47](https://user-images.githubusercontent.com/10012209/91648428-3e00a100-ea85-11ea-9d67-bd0d29671734.png)

**Comment by dan13ram** [comment]
Created a separate issue for subgraph at https://github.com/raid-guild/xdai-omnibridge/issues/19
