### ISSUE TITLE
Make UI responsive for smaller screens

### ISSUE THREAD

**Issue by dan13ram** [raid-guild/xdai-omnibridge#40]

**Comment by lucascerro** [comment]
![image](https://user-images.githubusercontent.com/49558/92185025-1dd83580-ee29-11ea-863e-7c336a389ab8.png)
by reducing font size from 1.875 to 1.25 rem on the deposit values, the screen works well down to 1200px width on the white box.

**Comment by lucascerro** [comment]
for screens smaller than 1200 I think a breakpoint would good here. switch to a vertical layout

**Comment by lucascerro** [comment]
![image](https://user-images.githubusercontent.com/49558/92186638-d1dbbf80-ee2d-11ea-9b77-3dd3b2eebe58.png)
Who made the designs? I think the left-right-arrow pattern kind of breaks down in smaller screens. Should I change it?

**Comment by lucascerro** [comment]
https://www.figma.com/file/Lht8RfHAn8BC4bCfFZSPoO/xDAI-stuff?node-id=5%3A2
