### ISSUE TITLE
fix amount input becomes too small for larger values

### ISSUE THREAD

**Issue by dan13ram** [raid-guild/xdai-omnibridge#60]
If the name of the token is really large, and amount value also is larger than 4-5 digits
then the amount value gets hidden and user has to move cursor over the input field to see the full amount.

possibly need to change design for this

**Comment by dan13ram** [comment]
I wonder if we can remove the balanceInUsd completely from the UI and move the token name to the first row
and move balance amount of tokens to the top-right. This also solves #56

**Comment by lucascerro** [comment]
In the following comment I recommended reducing fontsize on text input down to 1.25 from 1.875 rem. It still won't fit large names + 18 decimals, but should alleviate the problem. Let me know if it's still breaking in the tests?
https://github.com/raid-guild/xdai-omnibridge/issues/40#issuecomment-686826472

**Comment by dan13ram** [comment]
@lucascerro Yes it doesn't work in all cases. 
Also I think font should remain large since its the main user interaction apart from the buttons.

**Comment by dan13ram** [comment]
Check this out. I've tried making the amount input the full second row, and removing usd values.
https://www.figma.com/file/jxWMLXTzB7rDubpAArUDj0/Bridge-UI-App-(Copy)?node-id=560%3A32
I've given you edit permissions @lucascerro

**Comment by lucascerro** [comment]
what opened up the space for the digits was moving the token selector, right? I like the USD value. Or, rather, I hate not having it. Those "You're trading 1 eth for 29.345 link" messages don't help me at all

**Comment by lucascerro** [comment]
On second thought, since we'll be trading equivalent tokens, I guess USD values are really not that needed. The bridge is always for "stake to stake on xDai", right? Never "stake to xDAI on xDai"? In that case, agree with removing usd values

**Comment by dan13ram** [comment]
> On second thought, since we'll be trading equivalent tokens, I guess USD values are really not that needed. The bridge is always for "stake to stake on xDai", right? Never "stake to xDAI on xDai"? In that case, agree with removing usd values

Yes its always the same token. We just bridge it :) Also fetching USD values for every ERC20 token is next to impossible.
