### ISSUE TITLE
Select token modal

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/xdai-omnibridge#7]
Allow users to select a specific token on the "From" network, match the alternate on the corresponding network.

- Token list: https://github.com/raid-guild/default-token-list
- Search filters list down with a fuzzy match
- Add custom token opens custom token modal #8 

<img width="1055" alt="Screen Shot 2020-08-29 at 11 14 26 AM" src="https://user-images.githubusercontent.com/1778380/91641381-92564300-e9e9-11ea-8518-8c484441c831.png">

**Comment by befitsandpiper** [comment]
probably should use the raid-guild default token list repo instead?
https://github.com/raid-guild/default-token-list/tree/master/src/tokens

**Comment by dan13ram** [comment]
Yes we are gonna use our token-list
