### ISSUE TITLE
Custom token modal

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/xdai-omnibridge#8]
Allow the user to add a custom token by address. Comes from Select Token Modal #7 

- Look up the symbol and decimals for the contract
- Remember tokens added locally

<img width="1089" alt="Screen Shot 2020-08-29 at 11 14 15 AM" src="https://user-images.githubusercontent.com/1778380/91641463-363fee80-e9ea-11ea-8870-2722b344dc78.png">

**Comment by dan13ram** [comment]
merged #49
