### ISSUE TITLE
Show alert when adding invalid token

### ISSUE THREAD

**Issue by crisog** [raid-guild/xdai-omnibridge#86]
When I try to add a new custom token, I'm getting a few errors in the console. It won't let me copy/paste the address.

<img src="https://user-images.githubusercontent.com/40803711/93830178-7b4bef00-fc3d-11ea-8af8-8ff34a83b9e1.png" width="450" height="400">

Errors;
![image](https://user-images.githubusercontent.com/40803711/93830141-61121100-fc3d-11ea-9c90-839b4cc37949.png)

**Comment by dan13ram** [comment]
Hey @crisog, can you share more details such as selected network and token address?

**Comment by crisog** [comment]
> Hey @crisog, can you share more details such as selected network and token address?

Hey man! Sorry for the inconvenient, I just noticed that I had a Rinkeby token address in my clipboard instead of an xDai token.

**Comment by dan13ram** [comment]
@crisog I think its worth showing an alert or an error in this case.

**Comment by dan13ram** [comment]
Currently UI fails without any alert or error when user adds an invalid token address, 
we should show a simple alert when it is invalid.
