### ISSUE TITLE
Confirm transfer modal

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/xdai-omnibridge#9]
When the user selects Transfer, confirm the details of the transfer in modal #14 

- Continue submits the relay transaction to the current blockchain
  - on Ethereum Mainnet, `relayTokens()` will send the tokens to the mediator contract
  - on xDai, there's no approval necessary, call `transferAndCall()` to send to the xDai mediator contract.
- If the wrong network is connected, show the change network warning #6.
- On submit, show transaction confirmations #10 

<img width="1050" alt="Screen Shot 2020-08-29 at 11 18 31 AM" src="https://user-images.githubusercontent.com/1778380/91642185-e0217a00-e9ee-11ea-857d-54ab2fdbbc74.png">

**Comment by dan13ram** [comment]
Closing this issue as this is no longer valid as per the new figmas. 
Confirmation already happens as part of metamask signing.

**Comment by dan13ram** [comment]
Use the latest figma. frame #25 in https://www.figma.com/file/6Wjib8BbIUQOxJMxTmW5pF/Bridge-UI-App?node-id=441%3A455

![Screenshot from 2020-09-02 18:51:37](https://user-images.githubusercontent.com/10012209/91988822-5d315400-ed4d-11ea-8652-a7d690580c4f.png)
