### ISSUE TITLE
Use wallet provider where possible

### ISSUE THREAD

**Issue by dan13ram** [raid-guild/xdai-omnibridge#96]
Currently we are using InfuraProvider for most read calls and using WalletProvider only for write calls.
In order to reduce the read calls on our InfuraProvider, we must move to using the WalletProvider whenever available.

**Comment by brossetti1** [comment]
@dan13ram curious if you could answer a question on this one just out of my curiosity. Not sure if you are tackling it already, but is the WalletProvider we want to switch to built in to `WalletConnectProvider from '@walletconnect/web3-provider';` or do we have to configure a new provider and replace the calls to Infura. Just looking for a high level description of what would solve this one if you have a few spare minutes to give.

**Comment by scottrepreneur** [comment]
That `WalletConnectProvider` should do it @brossetti1!

**Comment by dan13ram** [comment]
Hey we don't need to configure a new provider.
Some calls are made to read users balance, token limits etc.

Most of the read calls are made using the infura provider that we create.
But this is adding load on our infura due to large number of calls.

So we need to replace these calls and make them using the wallet provider
(that the user connects with using web3modal).

**Comment by dan13ram** [comment]
Involves tracking down these calls and changing the method calls and using
web3modal's ethersProvider object whenever we have it so that we don't use
the infura provider.

Hope that gives you a better description/idea. Let me know if you need more
clarity.

**Comment by brossetti1** [comment]
https://github.com/raid-guild/xdai-omnibridge/pull/105 so I took a stab at this, I would highly recommend checking over this one before merging :) 

https://github.com/raid-guild/xdai-omnibridge/pull/105
