### ISSUE TITLE
migrate to official token lists

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/xdai-omnibridge#98]
Need to create an xDai tokenlist.org list for universal access

Here's the current `default-token-list`: https://github.com/raid-guild/default-token-list/blob/master/src/tokens/xdai.json

Need to create the schema here, upload to IPFS and point an ENS at it. Ross did a list for [LexDAO here](https://github.com/Uniswap/tokenlists-org/issues/2).
https://github.com/Uniswap/token-lists

Figure out if [Honeyswap](https://honeyswap.org) is using a list we should merge into.
http://tokens.honeyswap.org/

**Comment by brossetti1** [comment]
leaving honey-swaps tokenlist repo as a reference https://github.com/1Hive/default-token-list

**Comment by dan13ram** [comment]
Now we are using 
https://tokens.honeyswap.org/ for tokens on xdai, and 
https://tokens.uniswap.org/ for tokens on mainnet

In future, if we have user requests to add new tokens we can forward those requests to respective teams 
honeyswap list for xdai: https://github.com/1Hive/default-token-list
uniswap list mainnet: https://github.com/uniswap/default-token-list
